import { cssAll, cssTimeFullMatch, cubicBezierFunc, stepsFunc, cssEasingFunction } from './css-value';
import { containerElements, filterPrimitiveElements, gradientElements, graphicsElements, newViewportsElements, shapeElements, textContentElements } from './definitions';
import { alignmentBaseline, alignX, alignY, animateTransformType, blendMode, calcMode, channel, crossOrigin, dur, edgeMode, feColorMatrixType, feFuncType, feTurbulenceType, inVal, isolationMode, lengthAdjust, markerUnit, method, operater, operater1, orient, referrer, restart, spreadMethod, target, units } from './enum';
import { angelFullMatch, clockFullMatch, controlPointsFullMatch, cssNameFullMatch, cssNameSpaceSeparatedFullMatch, indentFullMatch, integerFullMatch, langFullMatch, lengthPairFullMatch, lengthPairListFullMatch, lengthPercentageFullMatch, lengthPercentageListFullMatch, mediaTypeFullMatch, nameFullMatch, numberFullMatch, numberListFullMatch, numberOptionalFullMatch, numberSemiSepatatedFullMatch, pathFullMatch, percentageFullMatch, preservAspectRatioFullMatch, timeListFullMatch, transformListFullMatch, URIFullMatch, viewBoxFullMatch } from './syntax';

const shapeAndText = shapeElements.concat(textContentElements);
const viewport = ['pattern', 'marker'].concat(newViewportsElements);
const useContainerGraphics = ['use'].concat(containerElements, graphicsElements);
const colorApply = ['animate'].concat(useContainerGraphics, gradientElements);

interface IRegularAttrDefine {
	[propName: string]: IRegularAttr;
}

const _regularAttr: IRegularAttrDefine = {
	'accumulate': {
		name: 'accumulate',
		legalValues: [{
			type: 'string',
			value: 'none',
		}, {
			type: 'string',
			value: 'sum',
		}],
		initValue: 'none',
		applyTo: [],
	},
	'additive': {
		name: 'additive',
		legalValues: [{
			type: 'string',
			value: 'replace',
		}, {
			type: 'string',
			value: 'sum',
		}],
		initValue: 'replace',
		applyTo: [],
	},
	'amplitude': {
		name: 'amplitude',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '1',
		applyTo: [],
	},
	'attributeName': {
		name: 'attributeName',
		legalValues: [{
			type: 'attr',
		}],
		initValue: '',
		applyTo: [],
	},
	'azimuth': {
		name: 'azimuth',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '0',
		applyTo: [],
	},
	'baseFrequency': {
		name: 'baseFrequency',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberOptionalFullMatch,
		}],
		initValue: '0',
		applyTo: [],
	},
	'begin': {
		name: 'begin',
		legalValues: [{
			type: 'reg',
			value: timeListFullMatch,
		}],
		initValue: '0s',
		applyTo: [],
	},
	'bias': {
		name: 'bias',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '0',
		applyTo: [],
	},
	'by': {
		name: 'by',
		legalValues: [{
			type: 'reg',
			value: lengthPairFullMatch,
			tag: ['animateMotion'],
		}],
		initValue: '',
		applyTo: [],
	},
	'calcMode': {
		name: 'calcMode',
		legalValues: [{
			type: 'enum',
			value: calcMode,
		}],
		initValue: '',
		applyTo: [],
	},
	'class': {
		name: 'class',
		animatable: true,
		legalValues: [{
			type: 'reg',
			value: cssNameSpaceSeparatedFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'clipPathUnits': {
		name: 'clipPathUnits',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: units,
		}],
		initValue: 'userSpaceOnUse',
		applyTo: [],
	},
	'crossorigin': {
		name: 'crossorigin',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: crossOrigin,
		}],
		initValue: '',
		applyTo: [],
	},
	'cx': {
		name: 'cx',
		couldBeStyle: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}],
		initValue: [{
			val: '50%',
			tag: ['radialGradient'],
		}, {
			val: '0',
			tag: ['circle', 'ellipse'],
		}],
		applyTo: ['circle', 'ellipse'],
	},
	'cy': {
		name: 'cy',
		couldBeStyle: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}],
		initValue: [{
			val: '50%',
			tag: ['radialGradient'],
		}, {
			val: '0',
			tag: ['circle', 'ellipse'],
		}],
		applyTo: ['circle', 'ellipse'],
	},
	'd': {
		name: 'd',
		animatable: true,
		legalValues: [{
			type: 'reg',
			value: pathFullMatch, // 这里用的是宽泛规则，严格正则是 pathFullMatchStrict ，但是浏览器存在纠错机制，使用严格正则会导致意外的过滤，纠错机制已在 compute-path 中
		}],
		initValue: '',
		applyTo: [],
	},
	'diffuseConstant': {
		name: 'diffuseConstant',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '1',
		applyTo: [],
	},
	'divisor': {
		name: 'divisor',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'download': {
		name: 'download',
		animatable: true,
		legalValues: [{
			type: 'reg',
			value: nameFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'dur': {
		name: 'dur',
		legalValues: [{
			type: 'reg',
			value: clockFullMatch,
		}, {
			type: 'enum',
			value: dur,
		}],
		initValue: '',
		applyTo: [],
	},
	'dx': {
		name: 'dx',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
			tag: ['feOffset', 'feDropShadow'],
		}, {
			type: 'reg',
			value: lengthPercentageListFullMatch,
			tag: ['text', 'tspan'],
		}],
		initValue: [{
			val: '2',
			tag: ['feOffset', 'feDropShadow'],
		}, {
			val: '',
			tag: ['tspan', 'text'],
		}],
		applyTo: [],
	},
	'dy': {
		name: 'dy',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
			tag: ['feOffset', 'feDropShadow'],
		}, {
			type: 'reg',
			value: lengthPercentageListFullMatch,
			tag: ['text', 'tspan'],
		}],
		initValue: [{
			val: '2',
			tag: ['feOffset', 'feDropShadow'],
		}, {
			val: '',
			tag: ['tspan', 'text'],
		}],
		applyTo: [],
	},
	'edgeMode': {
		name: 'edgeMode',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: edgeMode,
		}],
		initValue: [{
			val: 'duplicate',
			tag: ['feConvolveMatrix'],
		}, {
			val: 'none',
			tag: ['feGaussianBlur'],
		}],
		applyTo: [],
	},
	'elevation': {
		name: 'elevation',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '0',
		applyTo: [],
	},
	'end': {
		name: 'end',
		legalValues: [{
			type: 'reg',
			value: timeListFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'exponent': {
		name: 'exponent',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '1',
		applyTo: [],
	},
	'filterUnits': {
		name: 'filterUnits',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: units,
		}],
		initValue: 'objectBoundingBox',
		applyTo: [],
	},
	'fr': {
		name: 'fr',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}],
		initValue: '0%',
		applyTo: [],
	},
	'from': {
		name: 'from',
		legalValues: [{
			type: 'reg',
			value: lengthPairFullMatch,
			tag: ['animateMotion'],
		}],
		initValue: '',
		applyTo: [],
	},
	'fx': {
		name: 'fx',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'fy': {
		name: 'fy',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'gradientTransform': {
		name: 'gradientTransform',
		animatable: true,
		legalValues: [{
			type: 'reg',
			value: transformListFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'gradientUnits': {
		name: 'gradientUnits',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: units,
		}],
		initValue: 'objectBoundingBox',
		applyTo: [],
	},
	'height': {
		name: 'height',
		couldBeStyle: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}, {
			type: 'string',
			value: 'auto',
		}],
		initValue: [{
			val: '100%',
			tag: filterPrimitiveElements.concat(['svg']),
		}, {
			val: '120%',
			tag: ['filter', 'mask'],
		}, {
			val: '0',
			tag: ['pattern', 'rect', 'foreignObject'],
		}, {
			val: 'auto',
			tag: ['svg', 'image', 'rect', 'foreignObject'],
		}],
		applyTo: filterPrimitiveElements.concat(['filter', 'mask', 'pattern', 'svg', 'image', 'rect', 'foreignObject']),
	},
	'href': {
		name: 'href',
		animatable: true,
		maybeIRI: true,
		legalValues: [{
			type: 'reg',
			value: URIFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'hreflang': {
		name: 'hreflang',
		animatable: true,
		legalValues: [{
			type: 'reg',
			value: langFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'id': {
		name: 'id',
		legalValues: [{
			type: 'reg',
			value: nameFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'in': {
		name: 'in',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: inVal,
		}, {
			type: 'reg',
			value: indentFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'in2': {
		name: 'in2',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: inVal,
		}, {
			type: 'reg',
			value: indentFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'intercept': {
		name: 'intercept',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '0',
		applyTo: [],
	},
	'isolation': { // https://www.w3.org/TR/SVG/styling.html#RequiredProperties
		name: 'isolation',
		legalValues: [{
			type: 'enum',
			value: isolationMode,
		}],
		initValue: 'auto',
		applyTo: [],
	},
	'k1': {
		name: 'k1',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '0',
		applyTo: [],
	},
	'k2': {
		name: 'k2',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '0',
		applyTo: [],
	},
	'k3': {
		name: 'k3',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '0',
		applyTo: [],
	},
	'k4': {
		name: 'k4',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '0',
		applyTo: [],
	},
	'kernelMatrix': {
		name: 'kernelMatrix',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberListFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'kernelUnitLength': {
		name: 'kernelUnitLength',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberOptionalFullMatch,
		}],
		initValue: '2 2',
		applyTo: [],
	},
	'keyPoints': {
		name: 'keyPoints',
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberSemiSepatatedFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'keySplines': {
		name: 'keySplines',
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: controlPointsFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'keyTimes': {
		name: 'keyTimes',
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberSemiSepatatedFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'lang': {
		name: 'lang',
		legalValues: [{
			type: 'reg',
			value: langFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'lengthAdjust': {
		name: 'lengthAdjust',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: lengthAdjust,
		}],
		initValue: 'spacing',
		applyTo: [],
	},
	'limitingConeAngle': {
		name: 'limitingConeAngle',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'markerHeight': {
		name: 'markerHeight',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}],
		initValue: '3',
		applyTo: [],
	},
	'markerUnits': {
		name: 'markerUnits',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: markerUnit,
		}],
		initValue: 'strokeWidth',
		applyTo: [],
	},
	'markerWidth': {
		name: 'markerWidth',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}],
		initValue: '3',
		applyTo: [],
	},
	'maskContentUnits': {
		name: 'maskContentUnits',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: units,
		}],
		initValue: 'userSpaceOnUse',
		applyTo: [],
	},
	'maskUnits': {
		name: 'maskUnits',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: units,
		}],
		initValue: 'objectBoundingBox',
		applyTo: [],
	},
	'max': {
		name: 'max',
		legalValues: [{
			type: 'reg',
			value: clockFullMatch,
		}, {
			type: 'string',
			value: 'media',
		}],
		initValue: '',
		applyTo: [],
	},
	'media': {
		name: 'media',
		legalValues: [],
		initValue: [{
			val: 'all',
			tag: ['css'],
		}],
		applyTo: [],
	},
	'method': {
		name: 'method',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: method,
		}],
		initValue: 'align',
		applyTo: [],
	},
	'min': {
		name: 'min',
		legalValues: [{
			type: 'reg',
			value: clockFullMatch,
		}, {
			type: 'string',
			value: 'media',
		}],
		initValue: '0',
		applyTo: [],
	},
	'mode': {
		name: 'mode',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: blendMode,
		}],
		initValue: 'normal',
		applyTo: [],
	},
	'numOctaves': {
		name: 'numOctaves',
		animatable: true,
		legalValues: [{
			type: 'reg',
			value: integerFullMatch,
		}],
		initValue: '1',
		applyTo: [],
	},
	'offset': {
		name: 'offset',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}, {
			type: 'reg',
			value: percentageFullMatch,
			tag: ['stop'],
		}],
		initValue: '0',
		applyTo: [],
	},
	'operator': {
		name: 'operator',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: operater,
			tag: ['feComposite'],
		}, {
			type: 'enum',
			value: operater1,
			tag: ['feMorphology'],
		}],
		initValue: [{
			val: 'over',
			tag: ['feComposite'],
		}, {
			val: 'erode',
			tag: ['feMorphology'],
		}],
		applyTo: [],
	},
	'order': {
		name: 'order',
		animatable: true,
		legalValues: [{
			type: 'reg',
			value: numberOptionalFullMatch,
		}],
		initValue: '3',
		applyTo: [],
	},
	'orient': {
		name: 'orient',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}, {
			type: 'reg',
			value: angelFullMatch,
		}, {
			type: 'enum',
			value: orient,
		}],
		initValue: '0',
		applyTo: [],
	},
	'path': {
		name: 'path',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: pathFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'pathLength': {
		name: 'pathLength',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'patternContentUnits': {
		name: 'patternContentUnits',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: units,
		}],
		initValue: 'userSpaceOnUse',
		applyTo: [],
	},
	'patternTransform': {
		name: 'patternTransform',
		animatable: true,
		legalValues: [{
			type: 'reg',
			value: transformListFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'patternUnits': {
		name: 'patternUnits',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: units,
		}],
		initValue: 'objectBoundingBox',
		applyTo: [],
	},
	'ping': {
		name: 'ping',
		legalValues: [],
		initValue: '',
		applyTo: [],
	},
	'playbackorder': {
		name: 'playbackorder',
		legalValues: [{
			type: 'string',
			value: 'forwardonly',
		}, {
			type: 'string',
			value: 'all',
		}],
		initValue: 'all',
		applyTo: [],
	},
	'points': {
		name: 'points',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberListFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'pointsAtX': {
		name: 'pointsAtX',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '0',
		applyTo: [],
	},
	'pointsAtY': {
		name: 'pointsAtY',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '0',
		applyTo: [],
	},
	'pointsAtZ': {
		name: 'pointsAtZ',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '0',
		applyTo: [],
	},
	'preserveAlpha': {
		name: 'preserveAlpha',
		animatable: true,
		legalValues: [{
			type: 'string',
			value: 'false',
		}, {
			type: 'string',
			value: 'true',
		}],
		initValue: 'false',
		applyTo: [],
	},
	'preserveAspectRatio': {
		name: 'preserveAspectRatio',
		animatable: true,
		legalValues: [{
			type: 'reg',
			value: preservAspectRatioFullMatch,
		}],
		initValue: [{
			val: 'xMidYMid',
			tag: ['canvas', 'feImage', 'image', 'marker', 'pattern', 'svg', 'symbol', 'view'],
		}, {
			val: 'xMidYMid meet',
			tag: ['canvas', 'feImage', 'image', 'marker', 'pattern', 'svg', 'symbol', 'view'],
		}],
		applyTo: [],
	},
	'primitiveUnits': {
		name: 'primitiveUnits',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: units,
		}],
		initValue: 'userSpaceOnUse.',
		applyTo: [],
	},
	'r': {
		name: 'r',
		couldBeStyle: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}],
		initValue: [{
			val: '50%',
			tag: ['radialGradient'],
		}, {
			val: '0',
			tag: ['circle'],
		}],
		applyTo: ['circle'],
	},
	'radius': {
		name: 'radius',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberOptionalFullMatch,
		}],
		initValue: '0',
		applyTo: [],
	},
	'refX': {
		name: 'refX',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}, {
			type: 'enum',
			value: alignX,
		}],
		initValue: [{
			val: '0',
			tag: ['marker'],
		}],
		applyTo: [],
	},
	'refY': {
		name: 'refY',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}, {
			type: 'enum',
			value: alignY,
		}],
		initValue: [{
			val: '0',
			tag: ['marker'],
		}],
		applyTo: [],
	},
	'referrerpolicy': {
		name: 'referrerpolicy',
		legalValues: [{
			type: 'enum',
			value: referrer,
		}],
		initValue: '',
		applyTo: [],
	},
	'rel': {
		name: 'rel',
		animatable: true,
		legalValues: [],
		initValue: '',
		applyTo: [],
	},
	'repeatCount': {
		name: 'repeatCount',
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}, {
			type: 'string',
			value: 'indefinite',
		}],
		initValue: '',
		applyTo: [],
	},
	'repeatDur': {
		name: 'repeatDur',
		legalValues: [{
			type: 'reg',
			value: clockFullMatch,
		}, {
			type: 'string',
			value: 'indefinite',
		}],
		initValue: '',
		applyTo: [],
	},
	'requiredExtensions': {
		name: 'requiredExtensions',
		legalValues: [],
		initValue: '',
		applyTo: [],
	},
	'restart': {
		name: 'restart',
		legalValues: [{
			type: 'enum',
			value: restart,
		}],
		initValue: 'always',
		applyTo: [],
	},
	'result': {
		name: 'result',
		animatable: true,
		legalValues: [{
			type: 'reg',
			value: cssNameFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'rotate': {
		name: 'rotate',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberListFullMatch,
			tag: ['text', 'tspan'],
		}, {
			type: 'reg',
			value: numberFullMatch,
			tag: ['animateMotion'],
		}, {
			type: 'string',
			value: 'auto',
			tag: ['animateMotion'],
		}, {
			type: 'string',
			value: 'auto-reverse',
			tag: ['animateMotion'],
		}],
		initValue: '0',
		applyTo: [],
	},
	'rx': {
		name: 'rx',
		couldBeStyle: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}, {
			type: 'string',
			value: 'auto',
		}],
		initValue: 'auto',
		applyTo: ['ellipse', 'rect'],
	},
	'ry': {
		name: 'ry',
		couldBeStyle: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}, {
			type: 'string',
			value: 'auto',
		}],
		initValue: 'auto',
		applyTo: ['ellipse', 'rect'],
	},
	'scale': {
		name: 'scale',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '0',
		applyTo: [],
	},
	'seed': {
		name: 'seed',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '0',
		applyTo: [],
	},
	'side': {
		name: 'side',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'string',
			value: 'left',
		}, {
			type: 'string',
			value: 'right',
		}],
		initValue: 'left',
		applyTo: [],
	},
	'slope': {
		name: 'slope',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '1',
		applyTo: [],
	},
	'spacing': {
		name: 'spacing',
		animatable: true,
		legalValues: [{
			type: 'string',
			value: 'auto',
		}, {
			type: 'string',
			value: 'exact',
		}],
		initValue: 'exact',
		applyTo: [],
	},
	'specularConstant': {
		name: 'specularConstant',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '1',
		applyTo: [],
	},
	'specularExponent': {
		name: 'specularExponent',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '1',
		applyTo: [],
	},
	'spreadMethod': {
		name: 'spreadMethod',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: spreadMethod,
		}],
		initValue: 'pad',
		applyTo: [],
	},
	'startOffset': {
		name: 'startOffset',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}],
		initValue: '0',
		applyTo: [],
	},
	'stdDeviation': {
		name: 'stdDeviation',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberOptionalFullMatch,
		}],
		initValue: [{
			val: '2',
			tag: ['feDropShadow'],
		}, {
			val: '0',
			tag: ['feGaussianBlur'],
		}],
		applyTo: [],
	},
	'stitchTiles': {
		name: 'stitchTiles',
		animatable: true,
		legalValues: [{
			type: 'string',
			value: 'stitch',
		}, {
			type: 'string',
			value: 'noStitch',
		}],
		initValue: 'noStitch',
		applyTo: [],
	},
	'style': {
		name: 'style',
		legalValues: [],
		initValue: '',
		applyTo: [],
	},
	'surfaceScale': {
		name: 'surfaceScale',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '1',
		applyTo: [],
	},
	'systemLanguage': {
		name: 'systemLanguage',
		legalValues: [],
		initValue: '',
		applyTo: [],
	},
	'tabindex': {
		name: 'tabindex',
		legalValues: [{
			type: 'reg',
			value: integerFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'tableValues': {
		name: 'tableValues',
		animatable: true,
		legalValues: [{
			type: 'reg',
			value: numberListFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'target': {
		name: 'target',
		animatable: true,
		legalValues: [{
			type: 'reg',
			value: nameFullMatch,
		}, {
			type: 'enum',
			value: target,
		}],
		initValue: '_self',
		applyTo: [],
	},
	'targetX': {
		name: 'targetX',
		animatable: true,
		legalValues: [{
			type: 'reg',
			value: integerFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'targetY': {
		name: 'targetY',
		animatable: true,
		legalValues: [{
			type: 'reg',
			value: integerFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'textLength': {
		name: 'textLength',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'timelinebegin': {
		name: 'timelinebegin',
		legalValues: [{
			type: 'string',
			value: 'loadend',
		}, {
			type: 'string',
			value: 'loadbegin',
		}],
		initValue: 'loadend',
		applyTo: [],
	},
	'title': {
		name: 'title',
		legalValues: [],
		initValue: '',
		applyTo: [],
	},
	'to': {
		name: 'to',
		legalValues: [{
			type: 'reg',
			value: lengthPairFullMatch,
			tag: ['animateMotion'],
		}],
		initValue: '',
		applyTo: [],
	},
	'type': {
		name: 'type',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: animateTransformType,
			tag: ['animateTransform'],
		}, {
			type: 'enum',
			value: feColorMatrixType,
			tag: ['feColorMatrix'],
		}, {
			type: 'enum',
			value: feFuncType,
			tag: ['feFuncA', 'feFuncB', 'feFuncG', 'feFuncR'],
		}, {
			type: 'enum',
			value: feTurbulenceType,
			tag: ['feTurbulence'],
		}, {
			type: 'reg',
			value: mediaTypeFullMatch,
			tag: ['script'],
		}, {
			type: 'reg',
			value: mediaTypeFullMatch,
			tag: ['style'],
		}],
		initValue: [{
			val: 'translate',
			tag: ['animateTransform'],
		}, {
			val: 'matrix',
			tag: ['feColorMatrix'],
		}, {
			val: 'identity',
			tag: ['feFuncA', 'feFuncB', 'feFuncG', 'feFuncR'],
		}, {
			val: 'turbulence',
			tag: ['feTurbulence'],
		}, {
			val: 'application/ecmascript',
			tag: ['script'],
		}, {
			val: 'text/css',
			tag: ['style'],
		}],
		applyTo: [],
	},
	'values': {
		name: 'values',
		animatable: true,
		maybeAccurateNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberListFullMatch,
			tag: ['feColorMatrix'],
		}, {
			type: 'reg',
			value: lengthPairListFullMatch,
			tag: ['animateMotion'],
		}],
		initValue: '',
		applyTo: [],
	},
	'viewBox': {
		name: 'viewBox',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: viewBoxFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'width': {
		name: 'width',
		couldBeStyle: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}, {
			type: 'string',
			value: 'auto',
		}],
		initValue: [{
			val: '100%',
			tag: filterPrimitiveElements.concat(['svg']),
		}, {
			val: '120%',
			tag: ['filter', 'mask'],
		}, {
			val: '0',
			tag: ['pattern', 'rect', 'foreignObject'],
		}, {
			val: 'auto',
			tag: ['svg', 'image', 'rect', 'foreignObject'],
		}],
		applyTo: filterPrimitiveElements.concat(['filter', 'mask', 'pattern', 'svg', 'image', 'rect', 'foreignObject']),
	},
	'x': {
		name: 'x',
		couldBeStyle: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
			tag: filterPrimitiveElements.concat(['filter', 'mask', 'pattern', 'svg', 'rect', 'image', 'foreignObject']),
		}, {
			type: 'reg',
			value: numberFullMatch,
			tag: ['fePointLight', 'feSpotLight'],
		}, {
			type: 'reg',
			value: lengthPercentageListFullMatch,
			tag: ['text', 'tspan'],
		}, {
			type: 'string',
			value: 'auto',
		}],
		initValue: [{
			val: '0%',
			tag: filterPrimitiveElements,
		}, {
			val: '0',
			tag: ['fePointLight', 'feSpotLight', 'pattern', 'svg', 'rect', 'image', 'foreignObject', 'text'],
		}, {
			val: '-10%',
			tag: ['filter', 'mask'],
		}, {
			val: '',
			tag: ['tspan'],
		}],
		applyTo: filterPrimitiveElements.concat(['fePointLight', 'feSpotLight', 'filter', 'mask', 'pattern', 'svg', 'rect', 'image', 'foreignObject', 'text']),
	},
	'x1': {
		name: 'x1',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}, {
			type: 'string',
			value: 'auto',
		}],
		initValue: [{
			val: '0',
			tag: ['line'],
		}, {
			val: '0%',
			tag: ['linearGradient'],
		}],
		applyTo: [],
	},
	'x2': {
		name: 'x2',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}, {
			type: 'string',
			value: 'auto',
		}],
		initValue: [{
			val: '0',
			tag: ['line'],
		}, {
			val: '100%',
			tag: ['linearGradient'],
		}],
		applyTo: [],
	},
	'xChannelSelector': {
		name: 'xChannelSelector',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: channel,
		}],
		initValue: 'A',
		applyTo: [],
	},
	'xlink:href': {
		name: 'xlink:href',
		animatable: true,
		maybeIRI: true,
		legalValues: [{
			type: 'reg',
			value: URIFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'xlink:title': {
		name: 'xlink:title',
		legalValues: [],
		initValue: '',
		applyTo: [],
	},
	'xml:space': {
		name: 'xml:space',
		isUndef: true, // 此属性与本优化工具有冲突，没有实际意义
		legalValues: [{
			type: 'string',
			value: 'default',
		}, {
			type: 'string',
			value: 'preserve',
		}],
		initValue: 'default',
		applyTo: [],
	},
	'xmlns': {
		name: 'xmlns',
		legalValues: [{
			type: 'reg',
			value: URIFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'xmlns:xlink': {
		name: 'xmlns:xlink',
		legalValues: [{
			type: 'reg',
			value: URIFullMatch,
		}],
		initValue: '',
		applyTo: [],
	},
	'y': {
		name: 'y',
		couldBeStyle: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
			tag: filterPrimitiveElements.concat(['filter', 'mask', 'pattern', 'svg', 'rect', 'image', 'foreignObject']),
		}, {
			type: 'reg',
			value: lengthPercentageListFullMatch,
			tag: ['text', 'tspan'],
		}, {
			type: 'reg',
			value: numberFullMatch,
			tag: ['fePointLight', 'feSpotLight'],
		}, {
			type: 'string',
			value: 'auto',
		}],
		initValue: [{
			val: '0%',
			tag: filterPrimitiveElements,
		}, {
			val: '0',
			tag: ['fePointLight', 'feSpotLight', 'pattern', 'svg', 'rect', 'image', 'foreignObject', 'text'],
		}, {
			val: '-10%',
			tag: ['filter', 'mask'],
		}, {
			val: '',
			tag: ['tspan'],
		}],
		applyTo: filterPrimitiveElements.concat(['fePointLight', 'feSpotLight', 'filter', 'mask', 'pattern', 'svg', 'rect', 'image', 'foreignObject', 'text']),
	},
	'y1': {
		name: 'y1',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}, {
			type: 'string',
			value: 'auto',
		}],
		initValue: [{
			val: '0',
			tag: ['line'],
		}, {
			val: '0%',
			tag: ['linearGradient'],
		}],
		applyTo: [],
	},
	'y2': {
		name: 'y2',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: lengthPercentageFullMatch,
		}, {
			type: 'string',
			value: 'auto',
		}],
		initValue: [{
			val: '0',
			tag: ['line'],
		}, {
			val: '0%',
			tag: ['linearGradient'],
		}],
		applyTo: [],
	},
	'yChannelSelector': {
		name: 'yChannelSelector',
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: channel,
		}],
		initValue: 'A',
		applyTo: [],
	},
	'z': {
		name: 'z',
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [{
			type: 'reg',
			value: numberFullMatch,
		}],
		initValue: '0',
		applyTo: [],
	},
	'zoomAndPan': {
		name: 'zoomAndPan',
		animatable: true,
		legalValues: [{
			type: 'string',
			value: 'disable',
		}, {
			type: 'string',
			value: 'magnify',
		}],
		initValue: 'disable',
		applyTo: [],
	},

	// 下面是 property

	'alignment-baseline': {
		name: 'alignment-baseline',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [{
			type: 'enum',
			value: alignmentBaseline,
		}],
		initValue: 'baseline',
		applyTo: ['tspan', 'textPath'],
	},
	'all': {
		name: 'all',
		couldBeStyle: true,
		cantTrans: true,
		cantBeAttr: true,
		legalValues: [{
			type: 'enum',
			value: cssAll,
		}],
		initValue: '',
		applyTo: useContainerGraphics,
	},
	'animation-name': {
		name: 'animation-name',
		couldBeStyle: true,
		cantTrans: true,
		cantBeAttr: true,
		legalValues: [{
			type: 'reg',
			value: cssNameFullMatch,
		}],
		initValue: 'none',
		applyTo: useContainerGraphics,
	},
	'animation-duration': {
		name: 'animation-duration',
		maybeAccurateNumber: true,
		couldBeStyle: true,
		cantTrans: true,
		cantBeAttr: true,
		legalValues: [{
			type: 'reg',
			value: cssTimeFullMatch,
		}],
		initValue: '0',
		applyTo: useContainerGraphics,
	},
	'animation-timing-function': {
		name: 'animation-timing-function',
		maybeAccurateNumber: true,
		couldBeStyle: true,
		cantTrans: true,
		cantBeAttr: true,
		legalValues: [{
			type: 'enum',
			value: cssEasingFunction,
		}, {
			type: 'func',
			value: cubicBezierFunc,
		}, {
			type: 'func',
			value: stepsFunc,
		}],
		initValue: 'ease',
		applyTo: useContainerGraphics,
	},
	'animation-iteration-count': {
		name: 'animation-iteration-count',
		maybeSizeNumber: true,
		couldBeStyle: true,
		cantTrans: true,
		cantBeAttr: true,
		legalValues: [],
		initValue: '1',
		applyTo: useContainerGraphics,
	},
	'animation-direction': {
		name: 'animation-direction',
		couldBeStyle: true,
		cantTrans: true,
		cantBeAttr: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: useContainerGraphics,
	},
	'animation-play-state': {
		name: 'animation-play-state',
		couldBeStyle: true,
		cantTrans: true,
		cantBeAttr: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: useContainerGraphics,
	},
	'animation-delay': {
		name: 'animation-delay',
		maybeAccurateNumber: true,
		couldBeStyle: true,
		cantTrans: true,
		cantBeAttr: true,
		legalValues: [],
		initValue: '0',
		applyTo: useContainerGraphics,
	},
	'animation-fill-mode': {
		name: 'animation-fill-mode',
		couldBeStyle: true,
		cantTrans: true,
		cantBeAttr: true,
		legalValues: [],
		initValue: 'none',
		applyTo: useContainerGraphics,
	},
	'animation': {
		name: 'animation',
		couldBeStyle: true,
		cantTrans: true,
		cantBeAttr: true,
		legalValues: [],
		initValue: '',
		applyTo: useContainerGraphics,
	},
	'baseline-shift': {
		name: 'baseline-shift',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [],
		initValue: '0',
		applyTo: ['tspan', 'textPath'],
	},
	'clip': {
		name: 'clip',
		couldBeStyle: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [],
		initValue: 'auto',
		applyTo: viewport,
	},
	'clip-path': {
		name: 'clip-path',
		couldBeStyle: true,
		animatable: true,
		maybeFuncIRI: true,
		legalValues: [],
		initValue: 'none',
		applyTo: useContainerGraphics,
	},
	'clip-rule': {
		name: 'clip-rule',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'nonzero',
		applyTo: ['use'].concat(graphicsElements),
	},
	'color': {
		name: 'color',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeColor: true,
		legalValues: [],
		initValue: '',
		applyTo: ['feFlood', 'feDiffuseLighting', 'feSpecularLighting', 'stop'].concat(shapeAndText),
	},
	'color-interpolation': {
		name: 'color-interpolation',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'sRGB',
		applyTo: colorApply,
	},
	'color-interpolation-filters': {
		name: 'color-interpolation-filters',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'auto',
		applyTo: ['feSpotLight'].concat(filterPrimitiveElements),
	},
	'color-rendering': {
		name: 'color-rendering',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'auto',
		applyTo: colorApply,
	},
	'cursor': {
		name: 'cursor',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeFuncIRI: true,
		legalValues: [],
		initValue: 'auto',
		applyTo: useContainerGraphics,
	},
	'direction': {
		name: 'direction',
		couldBeStyle: true,
		inherited: true,
		legalValues: [],
		initValue: 'ltr',
		applyTo: textContentElements,
	},
	'display': {
		name: 'display',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: 'inline',
		applyTo: ['svg', 'g', 'switch', 'a', 'foreignObject', 'use'].concat(graphicsElements),
	},
	'dominant-baseline': {
		name: 'dominant-baseline',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'auto',
		applyTo: textContentElements,
	},
	'fill': {
		name: 'fill',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeColor: true,
		maybeFuncIRI: true,
		legalValues: [],
		initValue: [{
			val: 'black',
			tag: useContainerGraphics,
		}, {
			val: 'remove',
			tag: ['animate', 'animateMotion', 'animateTransform', 'set'],
		}],
		applyTo: ['animate', 'animateMotion', 'animateTransform', 'set'].concat(shapeAndText),
	},
	'fill-opacity': {
		name: 'fill-opacity',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeAlpha: true,
		legalValues: [],
		initValue: '1',
		applyTo: shapeAndText,
	},
	'fill-rule': {
		name: 'fill-rule',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'nonzero',
		applyTo: shapeAndText,
	},
	'filter': {
		name: 'filter',
		couldBeStyle: true,
		animatable: true,
		maybeFuncIRI: true,
		legalValues: [],
		initValue: 'none',
		applyTo: useContainerGraphics,
	},
	'flood-color': {
		name: 'flood-color',
		couldBeStyle: true,
		animatable: true,
		maybeColor: true,
		legalValues: [],
		initValue: 'black',
		applyTo: ['feFlood'],
	},
	'flood-opacity': {
		name: 'flood-opacity',
		couldBeStyle: true,
		maybeAlpha: true,
		legalValues: [],
		initValue: '1',
		applyTo: ['feFlood'],
	},
	'font': {
		name: 'font',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [],
		initValue: '',
		applyTo: textContentElements,
	},
	'font-family': {
		name: 'font-family',
		couldBeStyle: true,
		inherited: true,
		legalValues: [],
		initValue: '',
		applyTo: textContentElements,
	},
	'font-feature-settings': {
		name: 'font-feature-settings',
		couldBeStyle: true,
		cantTrans: true,
		cantBeAttr: true,
		inherited: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: textContentElements,
	},
	'font-kerning': {
		name: 'font-kerning',
		couldBeStyle: true,
		cantTrans: true,
		cantBeAttr: true,
		inherited: true,
		legalValues: [],
		initValue: 'auto',
		applyTo: textContentElements,
	},
	'font-size': {
		name: 'font-size',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [],
		initValue: 'medium',
		applyTo: textContentElements,
	},
	'font-size-adjust': {
		name: 'font-size-adjust',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [],
		initValue: 'none',
		applyTo: textContentElements,
	},
	'font-stretch': {
		name: 'font-stretch',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: textContentElements,
	},
	'font-style': {
		name: 'font-style',
		couldBeStyle: true,
		inherited: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: textContentElements,
	},
	'font-variant': {
		name: 'font-variant',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: textContentElements,
	},
	'font-variant-ligatures': {
		name: 'font-variant-ligatures',
		couldBeStyle: true,
		inherited: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: textContentElements,
	},
	'font-variant-position': {
		name: 'font-variant-position',
		couldBeStyle: true,
		inherited: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: textContentElements,
	},
	'font-variant-caps': {
		name: 'font-variant-caps',
		couldBeStyle: true,
		inherited: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: textContentElements,
	},
	'font-variant-numeric': {
		name: 'font-variant-numeric',
		couldBeStyle: true,
		inherited: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: textContentElements,
	},
	'font-variant-east-asian': {
		name: 'font-variant-east-asian',
		couldBeStyle: true,
		inherited: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: textContentElements,
	},
	'font-weight': {
		name: 'font-weight',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: textContentElements,
	},
	'image-rendering': {
		name: 'image-rendering',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'auto',
		applyTo: ['image'],
	},
	'inline-size': {
		name: 'inline-size',
		couldBeStyle: true,
		maybeSizeNumber: true,
		animatable: true,
		legalValues: [],
		initValue: '0',
		applyTo: ['text'],
	},
	'letter-spacing': {
		name: 'letter-spacing',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: textContentElements,
	},
	'lighting-color': {
		name: 'lighting-color',
		couldBeStyle: true,
		animatable: true,
		maybeColor: true,
		legalValues: [],
		initValue: 'white',
		applyTo: ['feDiffuseLighting', 'feSpecularLighting'],
	},
	'line-height': {
		name: 'line-height',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeColor: true,
		maybeSizeNumber: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: ['text'],
	},
	'marker': {
		name: 'marker',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeFuncIRI: true,
		legalValues: [],
		initValue: 'none',
		applyTo: shapeElements,
	},
	'marker-end': {
		name: 'marker-end',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeFuncIRI: true,
		legalValues: [],
		initValue: 'none',
		applyTo: shapeElements,
	},
	'marker-mid': {
		name: 'marker-mid',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeFuncIRI: true,
		legalValues: [],
		initValue: 'none',
		applyTo: shapeElements,
	},
	'marker-start': {
		name: 'marker-start',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeFuncIRI: true,
		legalValues: [],
		initValue: 'none',
		applyTo: shapeElements,
	},
	'mask': {
		name: 'mask',
		couldBeStyle: true,
		animatable: true,
		maybeFuncIRI: true,
		legalValues: [],
		initValue: 'none',
		applyTo: useContainerGraphics,
	},
	'mask-image': {
		name: 'mask-image',
		couldBeStyle: true,
		animatable: true,
		maybeFuncIRI: true,
		legalValues: [],
		initValue: 'none',
		applyTo: useContainerGraphics,
	},
	'mask-mode': {
		name: 'mask-mode',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: 'match-source',
		applyTo: useContainerGraphics,
	},
	'mask-repeat': {
		name: 'mask-repeat',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: 'repeat',
		applyTo: useContainerGraphics,
	},
	'mask-position': {
		name: 'mask-position',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: '0% 0%',
		applyTo: useContainerGraphics,
	},
	'mask-clip': { // https://drafts.fxtf.org/css-masking-1/#the-mask-clip
		name: 'mask-clip',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: 'border-box',
		applyTo: useContainerGraphics,
	},
	'mask-origin': {
		name: 'mask-origin',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: 'border-box',
		applyTo: useContainerGraphics,
	},
	'mask-size': {
		name: 'mask-size',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: 'auto',
		applyTo: useContainerGraphics,
	},
	'mask-composite': {
		name: 'mask-composite',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: 'add',
		applyTo: useContainerGraphics,
	},
	'mix-blend-mode': {
		name: 'mix-blend-mode',
		couldBeStyle: true,
		cantTrans: true,
		cantBeAttr: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: useContainerGraphics,
	},
	'opacity': {
		name: 'opacity',
		couldBeStyle: true,
		animatable: true,
		maybeAlpha: true,
		legalValues: [],
		initValue: '1',
		applyTo: ['svg', 'g', 'symbol', 'marker', 'a', 'switch', 'use', 'unknown'].concat(graphicsElements),
	},
	'overflow': {
		name: 'overflow',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: 'visible',
		applyTo: viewport,
	},
	'paint-order': {
		name: 'paint-order',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: shapeAndText,
	},
	'pointer-events': {
		name: 'pointer-events',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'visiblePainted',
		applyTo: useContainerGraphics,
	},
	'shape-image-threshold': {
		name: 'shape-image-threshold',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: '0',
		applyTo: ['text'],
	},
	'shape-inside': {
		name: 'shape-inside',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: 'auto',
		applyTo: ['text'],
	},
	'shape-margin': {
		name: 'shape-margin',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: '0',
		applyTo: ['text'],
	},
	'shape-padding': {
		name: 'shape-padding',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: '',
		applyTo: ['text'],
	},
	'shape-rendering': {
		name: 'shape-rendering',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'auto',
		applyTo: shapeElements,
	},
	'shape-subtract': {
		name: 'shape-subtract',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: 'none',
		applyTo: ['text'],
	},
	'stop-color': {
		name: 'stop-color',
		couldBeStyle: true,
		animatable: true,
		maybeColor: true,
		legalValues: [],
		initValue: 'black',
		applyTo: ['stop'],
	},
	'stop-opacity': {
		name: 'stop-opacity',
		couldBeStyle: true,
		animatable: true,
		maybeAlpha: true,
		legalValues: [],
		initValue: '1',
		applyTo: ['stop'],
	},
	'stroke': {
		name: 'stroke',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeColor: true,
		maybeFuncIRI: true,
		legalValues: [],
		initValue: 'none',
		applyTo: shapeAndText,
	},
	'stroke-dasharray': {
		name: 'stroke-dasharray',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [],
		initValue: 'none',
		applyTo: shapeAndText,
	},
	'stroke-dashoffset': {
		name: 'stroke-dashoffset',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [],
		initValue: '0',
		applyTo: shapeAndText,
	},
	'stroke-linecap': {
		name: 'stroke-linecap',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'butt',
		applyTo: shapeAndText,
	},
	'stroke-linejoin': {
		name: 'stroke-linejoin',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'miter',
		applyTo: shapeAndText,
	},
	'stroke-miterlimit': {
		name: 'stroke-miterlimit',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [],
		initValue: '4',
		applyTo: shapeAndText,
	},
	'stroke-opacity': {
		name: 'stroke-opacity',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeAlpha: true,
		legalValues: [],
		initValue: '1',
		applyTo: shapeAndText,
	},
	'stroke-width': {
		name: 'stroke-width',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [],
		initValue: '1',
		applyTo: shapeAndText,
	},
	'text-anchor': {
		name: 'text-anchor',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'start',
		applyTo: textContentElements,
	},
	'text-decoration': {
		name: 'text-decoration',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: '',
		applyTo: textContentElements,
	},
	'text-decoration-line': {
		name: 'text-decoration-line',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: 'none',
		applyTo: textContentElements,
	},
	'text-decoration-style': {
		name: 'text-decoration-style',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: 'solid',
		applyTo: textContentElements,
	},
	'text-decoration-color': {
		name: 'text-decoration-color',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: 'currentcolor',
		applyTo: textContentElements,
	},
	'text-decoration-fill': {
		name: 'text-decoration-fill',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: '',
		applyTo: textContentElements,
	},
	'text-decoration-stroke': {
		name: 'text-decoration-stroke',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: '',
		applyTo: textContentElements,
	},
	'text-orientation': {
		name: 'text-orientation',
		couldBeStyle: true,
		inherited: true,
		legalValues: [],
		initValue: 'mixed',
		applyTo: textContentElements,
	},
	'text-overflow': {
		name: 'text-overflow',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: 'auto',
		applyTo: textContentElements,
	},
	'text-rendering': {
		name: 'text-rendering',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'auto',
		applyTo: ['text'],
	},
	'transform': {
		name: 'transform',
		animatable: true,
		couldBeStyle: true,
		cantTrans: true,
		legalValues: [{
			type: 'reg',
			value: transformListFullMatch,
		}],
		initValue: '',
		applyTo: useContainerGraphics,
	},
	'transform-box': {
		name: 'transform-box',
		couldBeStyle: true,
		cantTrans: true,
		cantBeAttr: true,
		animatable: true,
		legalValues: [],
		initValue: 'border-box',
		applyTo: useContainerGraphics,
	},
	'transform-origin': {
		name: 'transform-origin',
		animatable: true,
		couldBeStyle: true,
		cantTrans: true,
		maybeSizeNumber: true,
		legalValues: [],
		initValue: '',
		applyTo: useContainerGraphics,
	},
	'unicode-bidi': {
		name: 'unicode-bidi',
		couldBeStyle: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: textContentElements,
	},
	'vector-effect': {
		name: 'vector-effect',
		couldBeStyle: true,
		animatable: true,
		legalValues: [],
		initValue: 'none',
		applyTo: ['use'].concat(graphicsElements),
	},
	'visibility': {
		name: 'visibility',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'visible',
		applyTo: ['use', 'a'].concat(graphicsElements),
	},
	'white-space': {
		name: 'white-space',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: textContentElements,
	},
	'will-change': {
		name: 'will-change',
		couldBeStyle: true,
		legalValues: [],
		initValue: 'auto',
		applyTo: useContainerGraphics,
	},
	'word-spacing': {
		name: 'word-spacing',
		couldBeStyle: true,
		inherited: true,
		animatable: true,
		maybeSizeNumber: true,
		legalValues: [],
		initValue: 'normal',
		applyTo: textContentElements,
	},
	'writing-mode': {
		name: 'writing-mode',
		couldBeStyle: true,
		inherited: true,
		legalValues: [],
		initValue: [{
			val: 'lr-tb',
			tag: ['text'],
		}, {
			val: 'horizontal-tb',
			tag: ['text'],
		}],
		applyTo: ['text'],
	},
};

const undefAttr: IRegularAttr = {
	name: '',
	isUndef: true,
	legalValues: [],
	initValue: '',
	applyTo: [],
};

export const regularAttr = new Proxy(_regularAttr, {
	get(obj, prop: string): IRegularAttr {
		return prop in obj ? obj[prop] : undefAttr;
	},
});
